version: '3'

services:
    web:
        build: /brevets
        command: python -u flask_brevets.py
        ports:
            - 5556:5000
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb


    ourdb:
        image: mongo:latest
